// ignore_for_file: avoid_print

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_auth/firebase_auth.dart';

class FirestoreController {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseAuth _auth = FirebaseAuth.instance;

  void addmeetingToFirestore(String meetingName) async {
    try {
      await _firestore
          .collection("users")
          .doc(_auth.currentUser?.uid)
          .collection("meetings")
          .add({
        "meetingName": meetingName,
        "createdAt": DateTime.now(),
      });
    } catch (e) {
      print("addmeetingToFirestore: $e");
    }
  }
}

// When we use set then first we have to use doc to give unique id;
// But when we use add then unique id is generated by firebase itself.
